sudo: true

dist: trusty

env:
  - URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz

addons:
  chrome: stable

before_install:
- openssl aes-256-cbc -K $encrypted_b7e3b789fefa_key -iv $encrypted_b7e3b789fefa_iv
  -in assets/server.key.enc -out assets/server.key -d
- wget -qO- $URL | tar xJf -
- ./sfdx/install

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_AUTOUPDATE_DISABLE=true
- sfdx plugins:install salesforcedx
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername -a HubOrg
script:
- sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a ciorg
- sfdx force:source:push -u ciorg
- sfdx force:lightning:test:run -f config/lts-config.json -a Tests.app -u ciorg
- sleep 10
- sfdx force:org:delete -u ciorg -p